### ISSUE TITLE
Add tracing capabilities

### ISSUE THREAD

**Issue by cjihrig** [cjihrig/uvwasi#110]
Log the system call name and other useful debugging information.

**Comment by gengjiawen** [comment]
Any thing you have in mind ? Last time I read an article on tracing (written in Chinese), pretty blow my mind.

**Comment by cjihrig** [comment]
I really just meant debugging statements similar to [this](https://github.com/nodejs/node/blob/307c67be175b8fe7d9dd9e1b5ed55d928b73d66d/src/node_wasi.cc#L254). I recently did some work to embed uvwasi in wasm3 and found myself adding similar code while debugging. It would be great to just have it in place all the time.
