### ISSUE TITLE
Potential integration with wabt

### ISSUE THREAD

**Issue by sbc100** [cjihrig/uvwasi#118]
I started to investigate an integration with wabt.  So far I have just the tiniest start with an implementation , just hooking up proc_exit:

https://github.com/WebAssembly/wabt/pull/1411

I had a couple of questions:

1.  What do you think is the best way for a project like wabt to build against uvwasi.   The approach I took was to use `add_subdirectory`.  However that resulted in an error because both uvwasi and wabt both define the custom `check` target.   I hacked that target out locally and it seems to work.

2.  Do users of uvwasi actually need the `uv.h` headers?  Currently the public headers for `uvwasi` include the headers from the `uv` project.   Perhaps that is unavoidable?   It does mean that downstream projects need to add more include paths so it could be removed that would be a win.

**Comment by cjihrig** [comment]
> What do you think is the best way for a project like wabt to build against uvwasi. The approach I took was to use add_subdirectory. However that resulted in an error because both uvwasi and wabt both define the custom check target. I hacked that target out locally and it seems to work.

It looks like uvwasi can add logic similar to [this](https://github.com/libuv/libuv/blob/55dede5b6f730882d79f994138f0f23a7b28b119/CMakeLists.txt#L20-L22) to only define those targets if it is the root project. In the mean time, does `ExternalProject_Add` work as suggested [here](https://stackoverflow.com/questions/42692785/how-to-deal-with-target-name-conflicts-between-mercurial-repositories-and-subrep)?

> Do users of uvwasi actually need the uv.h headers? Currently the public headers for uvwasi include the headers from the uv project. Perhaps that is unavoidable? It does mean that downstream projects need to add more include paths so it could be removed that would be a win.

I agree. I think it should be possible by moving some things around. I'll look into it.

**Comment by sbc100** [comment]
> > What do you think is the best way for a project like wabt to build against uvwasi. The approach I took was to use add_subdirectory. However that resulted in an error because both uvwasi and wabt both define the custom check target. I hacked that target out locally and it seems to work.
> 
> It looks like uvwasi can add logic similar to [this](https://github.com/libuv/libuv/blob/55dede5b6f730882d79f994138f0f23a7b28b119/CMakeLists.txt#L20-L22) to only define those targets if it is the root project. In the mean time, does `ExternalProject_Add` work as suggested [here](https://stackoverflow.com/questions/42692785/how-to-deal-with-target-name-conflicts-between-mercurial-repositories-and-subrep)?
> 

if you could make that change that would be awesome.  I briefly looked at `ExternalProject_Add` but it seemed a little heavyweight, and it doesn't look like it works with git submodules.  Perhaps I should take another look.

> > Do users of uvwasi actually need the uv.h headers? Currently the public headers for uvwasi include the headers from the uv project. Perhaps that is unavoidable? It does mean that downstream projects need to add more include paths so it could be removed that would be a win.
> 
> I agree. I think it should be possible by moving some things around. I'll look into it.

Thanks!

**Comment by cjihrig** [comment]
FYI - I landed https://github.com/cjihrig/uvwasi/commit/89f039dc2ac8eef7f49cd510cb69385a2c30fa46 earlier. I didn't close this out yet because the uv.h header part of this issue is still outstanding.

**Comment by sbc100** [comment]
Great!  This worked for me.  Thanks.
