### ISSUE TITLE
Android support in CI

### ISSUE THREAD

**Issue by gengjiawen** [cjihrig/uvwasi#135]
Similar to https://github.com/libuv/libuv/pull/2858, but I am not sure.

cc @cjihrig

**Comment by cjihrig** [comment]
I expect that if libuv builds on Android, this project should also build pretty easily. I'm not opposed to adding such a check to the CI.

**Comment by gengjiawen** [comment]
https://github.com/wasm3/wasm3 already build uvwasi in android platform. I guess it make sense we add it. I can work on it :)
