### ISSUE TITLE
Should we integrate valgrind ?

### ISSUE THREAD

**Issue by gengjiawen** [cjihrig/uvwasi#46]
Not sure should we dealing with the following

![image](https://user-images.githubusercontent.com/3759816/68072478-3880ee80-fdc1-11e9-8795-004b29ec105e.png)

**Comment by cjihrig** [comment]
If there is a convenient way to add it as a CI workflow, I'd be open to it.

In the specific case you're showing here, the problem is that I just never bothered to `free()` the memory from the `malloc()` and `calloc()` calls at the end of the test.

**Comment by gengjiawen** [comment]
valgrind is pretty unusable in macOS and windows. I want to give asan a try :)
