### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cjihrig/uvwasi#83]
I would like to point out that identifiers like “[`__UVWASI_H__`](https://github.com/cjihrig/uvwasi/blob/f069863ffcf384eac6121a43697a5d7fa8c52432/include/uvwasi.h#L1 "Update candidate")” and “[`uvwasi__translate_uv_error`](https://github.com/cjihrig/uvwasi/blob/293ce7be7be0555c301ebfb46a2faa57902de784/src/uv_mapping.h#L9 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by bnoordhuis** [comment]
^ this is a bot

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
